/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtividadesRouteImport } from './routes/atividades'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as EnergiaRouteImport } from './routes/energia'
import { Route as EvidenciasRouteImport } from './routes/evidencias'
import { Route as HojeRouteImport } from './routes/hoje'
import { Route as MarcasRouteImport } from './routes/marcas'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ProspectsRouteImport } from './routes/prospects'
import { Route as ScoreboardRouteImport } from './routes/scoreboard'
import { Route as TorneirasIndexRouteImport } from './routes/torneiras.index'
import { Route as TorneirasIdRouteImport } from './routes/torneiras.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesRoute = AtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiaRoute = EnergiaRouteImport.update({
  id: '/energia',
  path: '/energia',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenciasRoute = EvidenciasRouteImport.update({
  id: '/evidencias',
  path: '/evidencias',
  getParentRoute: () => rootRouteImport,
} as any)
const HojeRoute = HojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasRoute = MarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsRoute = ProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardRoute = ScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TorneirasIndexRoute = TorneirasIndexRouteImport.update({
  id: '/torneiras/',
  path: '/torneiras/',
  getParentRoute: () => rootRouteImport,
} as any)
const TorneirasIdRoute = TorneirasIdRouteImport.update({
  id: '/torneiras/$id',
  path: '/torneiras/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/catalogo': typeof CatalogoRoute
  '/energia': typeof EnergiaRoute
  '/evidencias': typeof EvidenciasRoute
  '/hoje': typeof HojeRoute
  '/marcas': typeof MarcasRoute
  '/metas': typeof MetasRoute
  '/pipeline': typeof PipelineRoute
  '/prospects': typeof ProspectsRoute
  '/scoreboard': typeof ScoreboardRoute
  '/torneiras/$id': typeof TorneirasIdRoute
  '/torneiras/': typeof TorneirasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/catalogo': typeof CatalogoRoute
  '/energia': typeof EnergiaRoute
  '/evidencias': typeof EvidenciasRoute
  '/hoje': typeof HojeRoute
  '/marcas': typeof MarcasRoute
  '/metas': typeof MetasRoute
  '/pipeline': typeof PipelineRoute
  '/prospects': typeof ProspectsRoute
  '/scoreboard': typeof ScoreboardRoute
  '/torneiras/$id': typeof TorneirasIdRoute
  '/torneiras': typeof TorneirasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/catalogo': typeof CatalogoRoute
  '/energia': typeof EnergiaRoute
  '/evidencias': typeof EvidenciasRoute
  '/hoje': typeof HojeRoute
  '/marcas': typeof MarcasRoute
  '/metas': typeof MetasRoute
  '/pipeline': typeof PipelineRoute
  '/prospects': typeof ProspectsRoute
  '/scoreboard': typeof ScoreboardRoute
  '/torneiras/$id': typeof TorneirasIdRoute
  '/torneiras/': typeof TorneirasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atividades'
    | '/catalogo'
    | '/energia'
    | '/evidencias'
    | '/hoje'
    | '/marcas'
    | '/metas'
    | '/pipeline'
    | '/prospects'
    | '/scoreboard'
    | '/torneiras/$id'
    | '/torneiras/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atividades'
    | '/catalogo'
    | '/energia'
    | '/evidencias'
    | '/hoje'
    | '/marcas'
    | '/metas'
    | '/pipeline'
    | '/prospects'
    | '/scoreboard'
    | '/torneiras/$id'
    | '/torneiras'
  id:
    | '__root__'
    | '/'
    | '/atividades'
    | '/catalogo'
    | '/energia'
    | '/evidencias'
    | '/hoje'
    | '/marcas'
    | '/metas'
    | '/pipeline'
    | '/prospects'
    | '/scoreboard'
    | '/torneiras/$id'
    | '/torneiras/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtividadesRoute: typeof AtividadesRoute
  CatalogoRoute: typeof CatalogoRoute
  EnergiaRoute: typeof EnergiaRoute
  EvidenciasRoute: typeof EvidenciasRoute
  HojeRoute: typeof HojeRoute
  MarcasRoute: typeof MarcasRoute
  MetasRoute: typeof MetasRoute
  PipelineRoute: typeof PipelineRoute
  ProspectsRoute: typeof ProspectsRoute
  ScoreboardRoute: typeof ScoreboardRoute
  TorneirasIdRoute: typeof TorneirasIdRoute
  TorneirasIndexRoute: typeof TorneirasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades': {
      id: '/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia': {
      id: '/energia'
      path: '/energia'
      fullPath: '/energia'
      preLoaderRoute: typeof EnergiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidencias': {
      id: '/evidencias'
      path: '/evidencias'
      fullPath: '/evidencias'
      preLoaderRoute: typeof EvidenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoje': {
      id: '/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof HojeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects': {
      id: '/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof ProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard': {
      id: '/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof ScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torneiras/': {
      id: '/torneiras/'
      path: '/torneiras'
      fullPath: '/torneiras/'
      preLoaderRoute: typeof TorneirasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torneiras/$id': {
      id: '/torneiras/$id'
      path: '/torneiras/$id'
      fullPath: '/torneiras/$id'
      preLoaderRoute: typeof TorneirasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtividadesRoute: AtividadesRoute,
  CatalogoRoute: CatalogoRoute,
  EnergiaRoute: EnergiaRoute,
  EvidenciasRoute: EvidenciasRoute,
  HojeRoute: HojeRoute,
  MarcasRoute: MarcasRoute,
  MetasRoute: MetasRoute,
  PipelineRoute: PipelineRoute,
  ProspectsRoute: ProspectsRoute,
  ScoreboardRoute: ScoreboardRoute,
  TorneirasIdRoute: TorneirasIdRoute,
  TorneirasIndexRoute: TorneirasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
